### ISSUE TITLE
Screenshot Test

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/weihnachtsmarkt#23]
![weihnachtsmarkt-1](https://cloud.githubusercontent.com/assets/225698/6495200/1ead83f8-c2c8-11e4-80ee-3bf9a1fc4e4e.png)

**Comment by ubergesundheit** [comment]
:+1:

**Comment by webwurst** [comment]
Hehe, habe mal so einen Pro-Trick ausprobiert: Bilder kannst du per Drag-n-Drop in ein Issue ziehen. Kriegst dann direkt den Link dazu in Markup Form und kannst den in Readme etc. einfügen ,)

**Comment by webwurst** [comment]
![screen shot 2015-03-06](https://cloud.githubusercontent.com/assets/225698/6537666/7228e8c8-c459-11e4-9c0c-45167f5053be.png)
