### ISSUE TITLE
"Ich will.." Feature

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/weihnachtsmarkt#24]
Eine Funktion wo ein Benutzer sagen kann: "Ich will was essen", "Ich brauch ein Geschenk", "Ich will Glühwein trinken"

**Comment by milchada** [comment]
Und wo soll man diese Meldungen schicken?

**Comment by ubergesundheit** [comment]
Hi, 

dieses Repository beinhaltet den Code für die Weihnachtsmarkt App von Code for Münster mit den Daten von 2015 (oder 2014)

In der App gibt es in der oberen Hälfte ein Eingabefeld, dort kann man Begriffe eingeben nach denen dann die Stände gefiltert werden.

Ansonsten ist dieses Feature noch nicht weiter implementiert. Gerne kannst du daran arbeiten, es fehlen dann noch die Daten für 2017.

Viele Grüße!
